version: "3.10"
services:
  fastapi:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports:
      - "8000:8000"
    networks:
      - app_network

  streamlit:
    build:
      context: ./Streamlit
      dockerfile: Dockerfile
    container_name: streamlit_container
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    environment:
      - BACKEND_URL=http://fastapi:8000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
